In [4]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split, KFold, cross_val_score
from sklearn.utils import resample
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report
from sklearn.tree import DecisionTreeClassifier
import numpy as np

# Load dataset
iris = load_iris()
X = iris.data
y = iris.target

# 1. Holdout Validation
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
model = DecisionTreeClassifier(random_state=42)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

print("=== Holdout Validation ===")
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Precision (macro):", precision_score(y_test, y_pred, average='macro'))
print("Recall (macro):", recall_score(y_test, y_pred, average='macro'))
print("F1 Score (macro):", f1_score(y_test, y_pred, average='macro'))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))

# 2. K-Fold Cross Validation (K=5)
kf = KFold(n_splits=5, shuffle=True, random_state=42)
cv_scores = cross_val_score(model, X, y, cv=kf, scoring='accuracy')

print("\n=== K-Fold Cross Validation (5-fold) ===")
print("Fold Accuracies:", cv_scores)
print("Mean Accuracy:", np.mean(cv_scores))

# 3. Bootstrap Sampling
n_iterations = 100
bootstrap_scores = []

for i in range(n_iterations):
    X_bs, y_bs = resample(X, y, replace=True, random_state=i)
    model_bs = DecisionTreeClassifier(random_state=i)
    model_bs.fit(X_bs, y_bs)
    
    # Evaluate on the original data (not the bootstrap sample)
    score = model_bs.score(X, y)
    bootstrap_scores.append(score)

print("\n=== Bootstrap Sampling (100 iterations) ===")
print("Average Accuracy:", np.mean(bootstrap_scores))
print("Standard Deviation:", np.std(bootstrap_scores))


=== Holdout Validation ===
Accuracy: 1.0
Precision (macro): 1.0
Recall (macro): 1.0
F1 Score (macro): 1.0
Confusion Matrix:
 [[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      1.00      1.00        13
           2       1.00      1.00      1.00        13

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45


=== K-Fold Cross Validation (5-fold) ===
Fold Accuracies: [1.         0.96666667 0.93333333 0.93333333 0.93333333]
Mean Accuracy: 0.9533333333333335

=== Bootstrap Sampling (100 iterations) ===
Average Accuracy: 0.9811333333333333
Standard Deviation: 0.010156771140475689
